fields = [
        'Sample ID': [:],
        'Method name': [:],
        'Toxicity domain': [:],
        'Information domain': [:],
        'Date': [:],
        'Experiment ID': [:],
        'Organization abbreviation': [:],
        'Organisation full name': [:],
        'Name of PI': [:],
        'Person entering data': [:],
        'E-mail': [:],
        'Compound': [:],
        'Compound name of actual form used': [:],
        'CAS Number': [:],
        'SMILES': [:],
        'Supplier': [:],
        'Order number': [:],
        'Lot number': [:],
        'Compound form': [:],
        'Storage temperature of unsolved compound': [:],
        'Stock solvent': [:],
        'Stock concentration': [ type: Float.class ],
        'Stock concentration unit': [:],
        'Stock aliquot storage': [:],
        'Sample type': [:],
        'Organism': [:],
        'Organ': [:],
        'Dimension': [:],
        'Heterogeneity': [:],
        'Dynamics': [:],
        'Differentiation status': [:],
        'Complexity': [:],
        'Cell type': [:],
        'Cell name': [:],
        'Cell donor or lot': [:],
        'Cell batch': [:],
        'Cell passage': [:],
        'Sex': [:],
        'Contact inhibition': [:],
        'Seeding density': [:],
        'Population doubling time': [:],
        'Treatment modality': [:],
        'Dosage': [:],
        'Dose maintenance': [:],
        'Exposure time': [ type: Float.class ],
        'Exposure time unit': [:],
        'Treatment scheme': [:],
        'Concentration': [ type: Float.class ],
        'Concentration Unit': [:],
        'Plate format': [:],
        'Plate manufacturer': [:],
        'Cell pre-treatment': [:],
        'Coating': [:],
        'Coating lot': [:],
        'Medium': [:],
        'Medium provider': [:],
        'Medium lot': [:],
        '% Serum': [:],
        'Serum provider': [:],
        'Serum lot': [:],
        'Medium additive 1': [:],
        'Additive 1 provider': [:],
        'Additive 1 concentration': [ type: Float.class ],
        'Additive 1 concentration unit': [:],
        'Medium additive 2': [:],
        'Additive 2 provider': [:],
        'Additive 2 concentration': [ type: Float.class ],
        'Additive 2 concentration unit': [:],
        'Medium additive 3': [:],
        'Additive 3 provider': [:],
        'Additive 3 concentration': [ type: Float.class ],
        'Additive 3 concentration unit': [:],
        'Medium additive 4': [:],
        'Additive 4 provider': [:],
        'Additive 4 concentration': [ type: Float.class ],
        'Additive 4 concentration unit': [:],
        'Medium additive 5': [:],
        'Additive 5 provider': [:],
        'Additive 5 concentration': [ type: Float.class ],
        'Additive 5 concentration unit': [:],
        '% DMSO': [ type: Float.class ],
        'DMSO provider': [:],
        'Platewise or stack': [:],
        'Group ID': [ : ],
        'Biological replicate': [ type: Integer.class ],
        'Technical replicates': [ type: Integer.class ],
        'Number of Endpoints': [ type: Integer.class ],
        'Endpoint 2/1 measure': [:],
        'Endpoint 2/1 definition': [:],
        'Endpoint 2/1 type': [:],
        'Endpoint 2/1 readout method': [:],
        'Endpoint 2/1 normalized': [ type: Float.class ],
        'Endpoint 2/1 mean': [:],
        'Endpoint 2/1 standard deviation': [:],
        'Endpoint 3 measure': [:],
        'Endpoint 3 definition': [:],
        'Endpoint 3 type': [:],
        'Endpoint 3 readout method': [:],
        'Endpoint 3 normalized': [ type: Float.class ],
        'Endpoint 3 mean': [:],
        'Endpoint 3 standard diviation': [:]
]
